In [1]:
print("pert1 intermediate python")

pert1 intermediate python


In [6]:
import numpy as np

a= np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


# Numpy 1

In [8]:
np.__version__

'1.19.5'

In [12]:
#np.info = untuk mencari tahu informasi function tersebut
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [14]:
#error tidak memenuhi 
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In [16]:
#numpy 1 dimensi
a = np.array([1, 2, 3, 4]) 
b = np.array([5, 6, 7, 8])

print(a+b)
print(a*b)

[ 6  8 10 12]
[ 5 12 21 32]


In [19]:
#numpy 2 dimensi
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(a)

[[ 1  4  9 16]
 [25 36 49 64]]


In [24]:
#untuk mengecheck ukuran array
print(a.shape)

#untuk mengecheck ukuran array
print(a.size)

#untuk mengecheck ukuran array
print(a.dtype)




(2, 4)
8
int32


In [27]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]],dtype=float)
print(a)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [37]:
zeros_matrix = np.zeros(5)
print(zeros_matrix)
zeros_matrix2 = np.zeros((5,2))
print(zeros_matrix)
print(zeros_matrix2)

matrix_ones = np.ones(5)
print(matrix_ones)
print("matrix 2 dimention")
matrix_ones_2_dimention = np.ones((5,2))
print(matrix_ones_2_dimention)
print("matrix 3 dimention")
matrix_ones_3_dimention = np.ones((5,2,3))
print(matrix_ones_3_dimention)



[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
matrix 2 dimention
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
matrix 3 dimention
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# LATIHAN 1


In [40]:
data1 = np.ones((4,3))
print(data1)

data2 = np.array([[2,3,12,0],[3,9,3,4],[4,0,1,3]])
print(data2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2  3 12  0]
 [ 3  9  3  4]
 [ 4  0  1  3]]


In [42]:
data3 = np.ones(10)
print(data3.size)

10


In [46]:
data4 = np.ones((2,3,3))
print(data4)
data4.shape

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


(2, 3, 3)

In [58]:

counter1 = 0
counter2 = 0
data5 = np.array([])
while(counter1<5):
    temp = np.array([])
    while(counter2<3):
        temp.append([2])
    data5.append([temp])

print(data5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'