In [11]:
import numpy as np
from numpy import random

In [10]:
soal1 = np.zeros(10,dtype=int)
soal1[5-1] = 11
soal1


array([ 0,  0,  0,  0, 11,  0,  0,  0,  0,  0])

In [18]:
soal2 = random.randint(10,size=(2,3))
print("sebelum : ")
print(soal2)
soal2 = soal2.T #transponse

print("sesudah")
print(soal2)

sebelum : 
[[6 2 4]
 [6 7 5]]
sesudah
[[6 6]
 [2 7]
 [4 5]]


In [56]:
soal3 = np.zeros((10,10),dtype=int)
soal3[0,:] = 1
soal3[:,0] = 1
soal3[-1,:] = 1
soal3[:,-1] = 1
print(soal3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [5]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
print("akses [1,1,2]")
print(z[1,1,2])

akses [1,1,2]
10
