In [2]:
import numpy as np
from numpy import random

1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [4]:
soal1 = np.zeros(10,dtype=int)
soal1[5-1] = 11
soal1


array([ 0,  0,  0,  0, 11,  0,  0,  0,  0,  0])

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [5]:
soal2 = random.randint(10,size=(2,3))
print("sebelum : ")
print(soal2)
soal2 = soal2.T #transponse

print("sesudah")
print(soal2)

sebelum : 
[[8 6 9]
 [9 7 0]]
sesudah
[[8 9]
 [6 7]
 [9 0]]


3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

In [6]:
soal3 = np.zeros((10,10),dtype=int)
soal3[0,:] = 1
soal3[:,0] = 1
soal3[-1,:] = 1
soal3[:,-1] = 1
print(soal3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


4. Take a look at the following matrix. Access the [1,1,2]

In [7]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [8]:
soal4 = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
print("akses [1,1,2]")
print(soal4[1,1,2])

akses [1,1,2]
10
