In [6]:
import numpy as np
a = np.empty((2,3),dtype=int)
print(a)

[[1629495328  544433528 1702043706]
 [1852142961 1864394083 1852383334]]


In [9]:
# mulai materi

In [13]:
np.zeros([2,2]).size

4

In [19]:
#create range
x = np.arange(10)


[10 11 12 13 14 15 16 17 18 19]


In [23]:
#create range from 10 to 20
x = np.arange(10,20)#(start,stop)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
#create range from 10 to 20 kenaikan 2 kali
x = np.arange(-1,1,0.1)#(start,stop,step)
x

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18])

In [26]:
x = np.linspace(0,10,10)
x

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [29]:
from numpy import random
#random berdasarkan 0 sampai 1
#random.rand()


array([[0.31135489, 0.75577673, 0.84348123, 0.62074507, 0.84217291],
       [0.58607467, 0.78414845, 0.03847413, 0.15384247, 0.54391123],
       [0.78977248, 0.82258724, 0.88119205, 0.61081507, 0.74771227],
       [0.33431901, 0.73616049, 0.62685201, 0.9355058 , 0.76847941],
       [0.07869421, 0.09512742, 0.75333037, 0.95327079, 0.01167775]])

In [38]:
random.rand(5,5)

array([[0.84931804, 0.89039021, 0.15688208, 0.70995286, 0.84624274],
       [0.1568288 , 0.7410901 , 0.99454425, 0.95009722, 0.9784831 ],
       [0.69827388, 0.47965084, 0.89157254, 0.15573301, 0.46161004],
       [0.24820398, 0.16107984, 0.4392695 , 0.92490777, 0.12770504],
       [0.84287534, 0.35917609, 0.24556812, 0.88184888, 0.78031324]])

In [41]:
random.randint(10)

3

In [43]:
random.randint(2,10,size =(4,3,2))

array([[[2, 7],
        [6, 8],
        [9, 9]],

       [[8, 3],
        [8, 5],
        [2, 7]],

       [[5, 2],
        [4, 7],
        [8, 8]],

       [[9, 7],
        [2, 8],
        [4, 2]]])

In [44]:
#latihan

In [47]:
random.randint(1,100,size=5)

array([75, 32, 10, 42, 62])

In [70]:
random.randint(1,100,size=(2,5))


array([[63, 29, 91,  4, 23],
       [96,  7, 12, 84, 46]])

In [73]:
x = np.linspace(1.5,5.5,30)
x

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

In [85]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
#my_arr = np.append(my_arr,(10,11,12))
my_arr = np.append(my_arr,(10,11,12),axis=0)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 0)
print(c)
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 0)
print(c)

[[1629495328  544433528 1702043706]
 [1852142961 1864394083 1852383334]
 [         8          2          1]
 [         3          9          1]]
[[ 1  2  8]
 [ 5  8 10]
 [ 8  2  1]
 [ 3  9  1]]


In [92]:
# sorting np.sort()
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
a = np.array([1,2,3,4])
b = np.array([5,4,3,2])
c = np.array([])
c= np.concatenate((a,b),axis=1)
c


AxisError: axis 1 is out of bounds for array of dimension 1

In [109]:
a = np.arange(6)
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#latihan 2

In [134]:
x = np.array([])
x = random.rand(3,3)
x
x.reshape(3,3)

array([[0.98028037, 0.6067818 , 0.90232913],
       [0.69632143, 0.23287131, 0.52167385],
       [0.67580497, 0.24159963, 0.6560244 ]])

In [120]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

c = np.concatenate((a,b),axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [135]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [138]:
#convert array
a2 = a[:,np.newaxis]
a2


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [142]:
b = np.expand_dims(a,axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [143]:
data = np.array([1,2,3,4,5])
data[1]

2

In [145]:
data = np.array([1,2,3,4,5])
data[1:]

array([2, 3, 4, 5])

In [155]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(a[a<5])

devisible_by_2 = a[(a%2==0) & (a<=8)]
devisible_by_2


[1 2 3 4]


array([2, 4, 6, 8])

In [163]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(a[0:2,1:3])

[[2 3]
 [6 7]]


In [164]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [165]:
z.shape

(2, 2, 3)

In [171]:
z[0,1,0]

5

In [173]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
a3 = np.vstack((a1,a2))


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [176]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
a3 = np.hstack((a1,a2))
a3

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [181]:
x = np.arange(1, 25).reshape(2, 12)
x = np.hsplit(x,3)
x

list