# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [4]:
print(np.info(np.add))

None


## What is Array?

![](image/array.png)

In [5]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [6]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: ignored

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [7]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [8]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v

array([1, 2, 3, 4, 5])

In [9]:
# matrix: the argument to the array function is a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m

array([[1, 2, 3],
       [4, 5, 6]])

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [10]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [ ]:
a = [1,2,3]

In [13]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [11]:
v.shape

(5,)

In [12]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [14]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [15]:
m.dtype

dtype('int64')

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [16]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [17]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [18]:
#two dimension

zeros_matrix2 = np.zeros((5,2))

In [19]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Matrix ones

In [20]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [21]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2.shape

(3, 4, 2)

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

2. Create the following matrix
![](image/lat11.png)

3. Create a 2D matrix with size of 10

4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [22]:
m4 = np.array([
    [[1,2,3],
     [4,5,6],
     [7,8,9]],
    
    [[10,11,12],
     [13,14,15],
     [16,17,18]]
])
m4.shape

(2, 3, 3)

5. Make the following arrays from zeros arrays and with for loops
![](image/exercise1.png)

In [ ]:
m5 = np.zeros((5,3))
m5

NameError: ignored

In [ ]:
a = 10
for i in range (a):
    print(i)

0
1
2
3
4
5
6
7
8
9
